# Generated by Django 5.1.3 on 2024-11-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('param_type', models.CharField(choices=[('Аналоговый датчик', 'Аналоговый датчик'), ('Кран с электрическим приводом', 'Кран с электрическим приводом'), ('Электромагнитный клапан', 'Электромагнитный клапан'), ('Насос', 'Насос')], max_length=50)),
            ],
        ),
    ]
