# Generated by Django 5.1.3 on 2024-11-11 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modbus_studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MBS_device_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MBS_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MBS_system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MBS_param_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('device_type', models.ManyToManyField(to='modbus_studio.mbs_device_type')),
            ],
        ),
        migrations.CreateModel(
            name='MBS_param_value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Значение поля')),
                ('incrementable', models.BooleanField(default=False, verbose_name='Инкрементируемый')),
                ('init_increment_val', models.IntegerField(verbose_name='Начально значение инкремента')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modbus_studio.mbs_param_name')),
            ],
        ),
        migrations.AddField(
            model_name='mbs_device_type',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modbus_studio.mbs_project'),
        ),
        migrations.AddField(
            model_name='mbs_device_type',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modbus_studio.mbs_system'),
        ),
    ]
